/* eslint-disable prettier/prettier */
import {StyleSheet} from 'react-native';
export const styleText = StyleSheet.create({
  Display_Large: {
    fontWeight: '400',
    fontSize: 57,
    lineHeight: 64,
    letterSpacing: -0.25,
    fontFamily: 'Roboto-Black',
  },
  Display_Medium: {
    fontWeight: '400',
    fontSize: 45,
    lineHeight: 52,
    fontFamily: 'Roboto-Black',
  },
  Display_Small: {
    fontWeight: '400',
    fontSize: 36,
    lineHeight: 44,
    fontFamily: 'Roboto-Black',
  },
  Headline_Large: {
    fontWeight: '400',
    fontSize: 32,
    lineHeight: 40,
    fontFamily: 'Roboto-Black',
  },
  Headline_Medium: {
    fontWeight: '400',
    fontSize: 28,
    lineHeight: 36,
    fontFamily: 'Roboto-Black',
  },
  Headline_Small: {
    fontWeight: '400',
    fontSize: 24,
    lineHeight: 32,
    fontFamily: 'Roboto-Black',
  },
  Title_Large: {
    fontWeight: '400',
    fontSize: 22,
    lineHeight: 28,
    fontFamily: 'Roboto-Regular',
  },
  Title_Medium: {
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 24,
    fontFamily: 'Roboto-Medium',
    letterSpacing: 0.15,
  },
  Title_Small: {
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Roboto-Medium',
    letterSpacing: 0.1,
  },
  Lable_Large: {
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Roboto-Medium',
    letterSpacing: 0.1,
  },
  Lable_Medium: {
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 16,
    fontFamily: 'Roboto-Medium',
    letterSpacing: 0.5,
  },
  Lable_Small: {
    fontWeight: '500',
    fontSize: 11,
    lineHeight: 16,
    fontFamily: 'Roboto-Medium',
    letterSpacing: 0.5,
  },
  Body_Large: {
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.5,
    fontFamily: 'Roboto-Black',
  },
  Body_Medium: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 24,
    letterSpacing: 0.25,
    fontFamily: 'Roboto-Black',
  },
  Body_Small: {
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.4,
    fontFamily: 'Roboto-Black',
  },
  Splash_font: {
    fontWeight: '400',
    fontSize: 40,
    lineHeight: 50,
    alignItems: 'center',
    fontFamily: 'PhosphateInline',
  },
  Splash_font2: {
    fontWeight: '400',
    fontSize: 40,
    lineHeight: 60,
    alignItems: 'center',
    opacity: 0.6,
    fontFamily: 'PhosphateInline',
  },
  MPlus1: {
    fontWeight: '700',
    fontSize: 53,
    lineHeight: 67.84,
    fontFamily: 'MPLUS1p-Medium',
  },
});
