/* eslint-disable prettier/prettier */
import {StyleSheet} from 'react-native';
import {appSize} from '../config/AppConstant';
export const styleText = StyleSheet.create({
  Display_Large: {
    fontWeight: '400',
    fontSize: appSize(57),
    lineHeight: appSize(64),
    letterSpacing: -0.25,
    fontFamily: 'Roboto-Black',
  },
  Display_Medium: {
    fontWeight: '400',
    fontSize: appSize(45),
    lineHeight: appSize(52),
    fontFamily: 'Roboto-Black',
  },
  Display_Small: {
    fontWeight: '400',
    fontSize: appSize(36),
    lineHeight: appSize(44),
    fontFamily: 'Roboto-Black',
  },
  Headline_Large: {
    fontWeight: '400',
    fontSize: appSize(32),
    lineHeight: appSize(40),
    fontFamily: 'Roboto-Black',
  },
  Headline_Medium: {
    fontWeight: '400',
    fontSize: appSize(28),
    lineHeight: appSize(36),
    fontFamily: 'Roboto-Black',
  },
  Headline_Small: {
    fontWeight: '400',
    fontSize: appSize(24),
    lineHeight: appSize(32),
    fontFamily: 'Roboto-Black',
  },
  Title_Large: {
    fontWeight: '400',
    fontSize: appSize(22),
    lineHeight: appSize(28),
    fontFamily: 'Roboto-Regular',
  },
  Title_Medium: {
    fontWeight: '500',
    fontSize: appSize(16),
    lineHeight: appSize(24),
    fontFamily: 'Roboto-Medium',
    letterSpacing: appSize(0.15),
  },
  Title_Small: {
    fontWeight: '500',
    fontSize: appSize(14),
    lineHeight: appSize(20),
    fontFamily: 'Roboto-Medium',
    letterSpacing: appSize(0.1),
  },
  Lable_Large: {
    fontWeight: '500',
    fontSize: appSize(14),
    lineHeight: appSize(20),
    fontFamily: 'Roboto-Medium',
    letterSpacing: appSize(0.1),
  },
  Lable_Medium: {
    fontWeight: '500',
    fontSize: appSize(12),
    lineHeight: appSize(16),
    fontFamily: 'Roboto-Medium',
    letterSpacing: appSize(0.5),
  },
  Lable_Small: {
    fontWeight: '500',
    fontSize: appSize(11),
    lineHeight: appSize(16),
    fontFamily: 'Roboto-Medium',
    letterSpacing: appSize(0.5),
  },
  Body_Large: {
    fontWeight: '400',
    fontSize: appSize(16),
    lineHeight: appSize(24),
    letterSpacing: appSize(0.5),
    fontFamily: 'Roboto-Black',
  },
  Body_Medium: {
    fontWeight: '400',
    fontSize: appSize(14),
    lineHeight: appSize(24),
    letterSpacing: appSize(0.25),
    fontFamily: 'Roboto-Black',
  },
  Body_Small: {
    fontWeight: '400',
    fontSize: appSize(12),
    lineHeight: appSize(16),
    letterSpacing: appSize(0.4),
    fontFamily: 'Roboto-Black',
  },
  Splash_font: {
    fontWeight: '400',
    fontSize: appSize(40),
    lineHeight: appSize(50),
    alignItems: 'center',
    fontFamily: 'PhosphateInline',
  },
  Splash_font2: {
    fontWeight: '400',
    fontSize: appSize(40),
    lineHeight: appSize(60),
    alignItems: 'center',
    opacity: appSize(0.6),
    fontFamily: 'PhosphateInline',
  },
  MPlus1: {
    fontWeight: '700',
    fontSize: appSize(53),
    lineHeight: appSize(67.84),
    fontFamily: 'MPLUS1p-Medium',
  },
});
